version: "3.9"
services:
  db:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db:db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - .:/app

volumes:
  dbdata:
